language: haskell
before_install:
  - git submodule update --init --recursive
install:  
 - cd data-ringbuffer
 - cabal install
 - cd ..
 - cabal install --only-dependencies --enable-tests
 - cabal configure
 - cabal build
 - cabal test
notifications:
  email:
    - tonyday567@gmail.com
